redis:
  schema: ${IoT_HOME_REDIS_SCHEMA:redis}
  databaseName: ${IoT_HOME_REDIS_DATABASE_NAME:0}
  redisEndpoint: ${IoT_HOME_REDIS_ENDPOINT:54.38.55.55:6379}
  redisConnectionTimeout: ${IoT_HOME_REDIS_CONNECTION_TIMEOUT:30000}
spring:
  datasource:
    url: ******
    username: sa
    password: *****
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        order_inserts: true
        generate_statistics: true
        jdbc:
          batch_size: ${BATCH_SIZE:100}
job:
  cron: ${JOB_CRON:*/10 * * * * *}